# Generated by Django 3.0.8 on 2023-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idcourse', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('hour', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
